"use client";

import { useEffect, useState } from "react";

type Song = { id: number; artistId: number | null; artistName: string; title: string; image?: string; genres?: string[] | null };
type SiteImage = { id: number; fileName: string; url: string };
type Item = { itemId: number; customTitle?: string | null; customSubtitle?: string | null; customDescription?: string | null; customImage?: string | null; customHref?: string | null };
type Editing = Record<number, { genres?: boolean; image?: boolean }>;

export default function ArtistsEditorialPanel() {
  const [songs, setSongs] = useState<Song[]>([]); const [images, setImages] = useState<SiteImage[]>([]);
  const [hero, setHero] = useState<Item | null>(null); const [grid, setGrid] = useState<Item[]>([]); const [editing, setEditing] = useState<Editing>({}); const [status, setStatus] = useState("");
  useEffect(() => { void fetch("/api/admin/editorial/artists").then((response) => response.json()).then((data) => { setSongs(data.songs ?? []); setImages(data.images ?? []); setHero(data.hero); setGrid(data.artists ?? []); }); }, []);
  async function save(key: string, items: Item[]) { const response = await fetch(`/api/admin/editorial/artists/${key}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items }) }); setStatus(response.ok ? "Saved." : ((await response.json()).error ?? "Could not save.")); }
  function updateGridItem(index: number, changes: Partial<Item>) { setGrid((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item)); }
  function setEdit(index: number, field: "genres" | "image", value: boolean) { setEditing((current) => ({ ...current, [index]: { ...current[index], [field]: value } })); }
  async function upload(index: number, file: File) { setStatus("Uploading image…"); const body = new FormData(); body.set("file", file); const response = await fetch("/api/admin/media", { method: "POST", body }); const payload = await response.json(); if (response.ok) { updateGridItem(index, { customImage: payload.url }); setImages((current) => [{ id: Date.now(), fileName: file.name, url: payload.url }, ...current]); setEdit(index, "image", false); setStatus("Image uploaded — save supporting artists to publish it."); } else setStatus(payload.error ?? "Could not upload image."); }
  const usedArtistIds = new Set(grid.map((item) => songs.find((song) => song.id === item.itemId)?.artistId));

  return <section className="mt-10 rounded-2xl border border-white/10 bg-white/[0.04] p-6"><p className="text-xs uppercase tracking-[0.22em] text-pink">Artists page CMS</p><h2 className="mt-2 text-2xl font-semibold text-white">Featured artists</h2><div className="mt-6 grid gap-6 xl:grid-cols-2">
    <div className="rounded-xl border border-white/10 bg-black/15 p-5"><h3 className="text-lg text-white">Hero artist</h3><select value={hero?.itemId ?? ""} onChange={(event) => setHero({ itemId: Number(event.target.value) })} className="mt-3 w-full rounded bg-black/30 p-2 text-white"><option value="">Choose artist track…</option>{songs.map((song) => <option key={song.id} value={song.id}>{song.artistName} — {song.title}</option>)}</select>{hero ? <><input value={hero.customTitle ?? ""} onChange={(event) => setHero({ ...hero, customTitle: event.target.value })} placeholder="Badge" className="mt-3 w-full rounded bg-black/30 p-2 text-white" /><textarea value={hero.customSubtitle ?? ""} onChange={(event) => setHero({ ...hero, customSubtitle: event.target.value })} placeholder="Hero introduction" className="mt-3 h-24 w-full rounded bg-black/30 p-2 text-white" /><textarea value={hero.customDescription ?? ""} onChange={(event) => setHero({ ...hero, customDescription: event.target.value })} placeholder="Editorial write-up" className="mt-3 h-32 w-full rounded bg-black/30 p-2 text-white" /><button onClick={() => void save("artists_hero", [hero])} className="mt-3 rounded bg-pink px-4 py-2 text-white">Save hero</button></> : null}</div>
    <div className="rounded-xl border border-white/10 bg-black/15 p-5"><div className="flex justify-between gap-4"><div><h3 className="text-lg text-white">Supporting artists</h3><p className="text-sm text-fog">6–30 artists, each with a track.</p></div><button disabled={grid.length < 6 || grid.length > 30} onClick={() => void save("artists_grid", grid)} className="rounded bg-pink px-4 py-2 text-white disabled:opacity-40">Save</button></div><select defaultValue="" onChange={(event) => { const id = Number(event.target.value); const song = songs.find((entry) => entry.id === id); if (song && !usedArtistIds.has(song.artistId)) setGrid([...grid, { itemId: id }]); event.currentTarget.value = ""; }} className="mt-3 w-full rounded bg-black/30 p-2 text-white"><option value="">Add artist and track…</option>{songs.filter((song) => !usedArtistIds.has(song.artistId)).map((song) => <option key={song.id} value={song.id}>{song.artistName} — {song.title}</option>)}</select>
      <div className="mt-3 space-y-3">{grid.map((item, index) => { const song = songs.find((entry) => entry.id === item.itemId); const inheritedGenres = song?.genres?.join(", ") ?? ""; const genres = item.customSubtitle || inheritedGenres; const image = item.customImage || song?.image || ""; const editingItem = editing[index] ?? {}; return <div key={item.itemId} className="rounded border border-white/10 p-3 text-sm"><div className="flex gap-2"><span>{index + 1}</span><span className="flex-1 truncate text-white">{song ? `${song.artistName} — ${song.title}` : "Track"}</span><button disabled={!index} onClick={() => { const next = [...grid]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; setGrid(next); }}>↑</button><button disabled={index === grid.length - 1} onClick={() => { const next = [...grid]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; setGrid(next); }}>↓</button><button onClick={() => setGrid(grid.filter((_, itemIndex) => itemIndex !== index))} className="text-pink">Remove</button></div>
        <div className="mt-3 grid gap-3 sm:grid-cols-[1fr_auto]"><div>{editingItem.genres || !genres ? <input value={item.customSubtitle ?? inheritedGenres} onChange={(event) => updateGridItem(index, { customSubtitle: event.target.value })} placeholder="Add genres (e.g. Rock, Soul)" className="w-full rounded bg-black/30 p-2 text-white" /> : <div className="flex items-center justify-between gap-2 rounded bg-white/5 p-2"><span className="text-fog">{genres}</span><button type="button" onClick={() => setEdit(index, "genres", true)} className="text-xs text-pink">Edit genres</button></div>}</div><div>{image ? <div className="flex items-center gap-2"><img src={image} alt="" className="h-12 w-12 rounded object-cover" /><button type="button" onClick={() => setEdit(index, "image", true)} className="text-xs text-pink">Edit image</button></div> : <button type="button" onClick={() => setEdit(index, "image", true)} className="rounded border border-pink/40 px-3 py-2 text-xs text-pink">Add image</button>}</div></div>
        {editingItem.image ? <div className="mt-3 rounded border border-white/10 bg-black/20 p-3"><select value={item.customImage ?? ""} onChange={(event) => { updateGridItem(index, { customImage: event.target.value || null }); setEdit(index, "image", false); }} className="w-full rounded bg-black/30 p-2 text-white"><option value="">Use artist’s existing image</option>{images.map((siteImage) => <option key={siteImage.id} value={siteImage.url}>{siteImage.fileName}</option>)}</select><details className="mt-2"><summary className="cursor-pointer text-xs text-pink">Select from site assets</summary><div className="mt-2 grid max-h-48 grid-cols-4 gap-2 overflow-y-auto">{images.map((siteImage) => <button type="button" key={siteImage.id} onClick={() => { updateGridItem(index, { customImage: siteImage.url }); setEdit(index, "image", false); }} className="overflow-hidden rounded border border-white/10 hover:border-pink"><img src={siteImage.url} alt={siteImage.fileName} className="aspect-square w-full object-cover" /></button>)}</div></details><label className="mt-3 inline-block cursor-pointer text-xs text-pink">Upload a new image<input type="file" accept="image/*" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(index, file); event.currentTarget.value = ""; }} /></label></div> : null}</div>; })}</div>
    </div></div>{status ? <p className="mt-4 text-fog">{status}</p> : null}</section>;
}
