import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Disc3, FolderOpen, Images, Music2, NotebookPen, SlidersHorizontal } from "lucide-react";
import Container from "../../components/layout/Container";
import { Button } from "../../components/ui/button";
import { pageMetadata } from "../../lib/seo";

export const metadata = pageMetadata({
  title: "Track Version Control | Fully Open Records",
  description: "Document every stage of a song, from the first jam to the final master. Keep recordings, notes, images, instruments and studio settings together in one creative timeline.",
  path: "/track-version-control",
  image: "/artists/stone.webp"
});

const features = [
  { title: "Organise Ideas", copy: "Keep every version of a track in one place.", icon: FolderOpen },
  { title: "Add Notes", copy: "Record what you tried, what worked and what to try next.", icon: NotebookPen },
  { title: "Attach Images", copy: "Save photos of your setup, pedals, amp settings, lyrics, chords and more.", icon: Images },
  { title: "Track Progress", copy: "See the complete creative journey from the first idea to the mastered track.", icon: SlidersHorizontal }
];

const stages = [
  { title: "First Jam", annotation: "A SPARK\nOF AN IDEA", description: "Capture the raw idea. Voice memos, riffs, anything goes.", image: "/track-versions/first-jam.jpg", alt: "Guitar and amplifier rehearsal setup", caption: "Garage · 12th Jan 2024", notes: "Riff idea in E. Rough drums on phone. Needs a heavier middle section.", setup: ["Fender Telecaster", "Orange Crush 20", "No pedals"], rotation: "-rotate-2" },
  { title: "Rehearsal", annotation: "FINDING\nTHE SOUND", description: "Experiment and develop the arrangement.", image: "/track-versions/rehearsal.jpg", alt: "Pedalboard and rehearsal equipment", caption: "New pedal setup", notes: "Tried the new fuzz. Works well in the chorus. Tempo up to 128bpm.", setup: ["Gibson Les Paul", "Marshall DSL40", "Big Muff / Boss DD-7"], rotation: "rotate-1" },
  { title: "Demo", annotation: "TAKING\nSHAPE", description: "Record a focused demo to capture the full song structure.", image: "/track-versions/demo.jpg", alt: "Studio recording workspace", caption: "Demo v1", notes: "Full take with scratch vocals. Need to tighten the bridge and rework lyrics.", setup: ["Gibson Les Paul", "Universal Audio Apollo", "Logic Pro"], rotation: "-rotate-1" },
  { title: "Pre-master", annotation: "POLISHING\nTHE DETAIL", description: "Refine the mix and finalise the performance.", image: "/track-versions/pre-master.jpg", alt: "Mixing and studio equipment", caption: "Mix v3", notes: "New drum take. Vocals doubled. Added plate reverb. Feeling close now.", setup: ["Neve 1073", "API 2500", "Pro Tools"], rotation: "rotate-2" },
  { title: "Master", annotation: "READY\nFOR THE WORLD", description: "The final version, ready for release.", image: "/track-versions/master.jpg", alt: "Mastering equipment", caption: "Master v1", notes: "Final master approved. Loud but dynamic. Ready to release.", setup: ["Waves L2", "iZotope Ozone", "24bit / 48kHz"], rotation: "-rotate-1" }
] as const;

function StageDetail({ stage, index }: { stage: (typeof stages)[number]; index: number }) {
  return <div className="min-w-0"><div className="text-center"><h3 className="text-[15px] font-semibold uppercase tracking-[0.04em] text-white"><span className="mr-1.5 text-xs text-[#75b9f5]">{index + 1}.</span>{stage.title}</h3><p className="mx-auto mt-2 max-w-[12rem] text-[13px] leading-5 text-fog">{stage.description}</p></div><div className={`relative mx-auto mt-4 w-[calc(100%-10px)] max-w-[194px] overflow-hidden border-[5px] border-[#e8e4db] bg-[#e8e4db] p-1 shadow-[0_12px_24px_rgba(0,0,0,0.38)] ${stage.rotation}`}><div className="relative aspect-[4/3] overflow-hidden bg-black"><Image src={stage.image} alt={stage.alt} fill sizes="(max-width: 1023px) 72vw, 180px" className="object-cover grayscale" /></div><p className="px-1 pb-0.5 pt-1.5 text-center font-display text-[12px] italic text-[#111a28]">{stage.caption}</p></div><div className="mx-auto mt-4 max-w-[194px] rounded-md border border-[#5c7897]/25 bg-[#07111d]/80 px-3 py-2.5"><p className="font-meta text-[9px] uppercase tracking-[0.18em] text-[#98b7d5]">Notes</p><p className="mt-1.5 text-[12px] leading-[1.45] text-fog">{stage.notes}</p></div><div className="mx-auto mt-4 flex max-w-[194px] gap-2"><Music2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#75b9f5]" /><div><p className="font-meta text-[9px] uppercase tracking-[0.18em] text-[#98b7d5]">Setup</p><ul className="mt-1.5 space-y-0.5 text-[12px] leading-[1.4] text-fog">{stage.setup.map((item) => <li key={item}>{item}</li>)}</ul></div></div></div>;
}

export default function TrackVersionControlPage() {
  return <main className="overflow-hidden pb-14">
    <section className="relative border-b border-white/10 bg-[radial-gradient(circle_at_20%_28%,rgba(63,117,170,0.15),transparent_28%),linear-gradient(90deg,rgba(3,9,18,0.96),rgba(3,10,20,0.74))]"><Container><div className="relative grid min-h-[430px] items-center gap-7 py-10 md:py-12 lg:grid-cols-[45%_55%]"><div className="relative z-10 max-w-[31rem]"><p className="font-meta text-[11px] uppercase tracking-[0.3em] text-[#83bcf0]">Track Version Control</p><h1 className="mt-4 text-5xl font-semibold leading-[0.94] text-white md:text-[66px]">Every idea<br />has a journey.<br /><span className="font-normal text-[#b7c7dd]">Capture it all.</span></h1><p className="mt-5 max-w-[29rem] text-[15px] leading-6 text-[#bac8d8]">Keep a complete diary of your track&apos;s evolution — from the first jam to the final master. Store every version, add notes, photos and settings, and preserve the ideas and decisions that shaped the finished track.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/signup"><Button className="h-auto rounded-lg px-6 py-3">Start Your Journey</Button></Link><a href="#timeline"><Button variant="outline" className="h-auto rounded-lg border-[#7293b5]/45 px-6 py-3">See How It Works</Button></a></div></div><div className="relative h-[300px] overflow-hidden md:h-[390px] lg:-mr-6 lg:h-[440px]"><Image src="/track-version-control-banner-hero.png" alt="Guitarist performing in a dark studio" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover object-[65%_50%] grayscale contrast-125 brightness-75" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,9,18,1),rgba(3,9,18,0.3)_42%,rgba(3,9,18,0.06)),linear-gradient(0deg,rgba(3,9,18,0.7),transparent_55%)]" /><div className="absolute inset-0 opacity-30 mix-blend-screen bg-[url('/bg/cosmic-blue-v2.png')] bg-cover" /></div></div></Container></section>

    <section className="border-b border-white/10 bg-[#030914]/75"><Container><div className="grid divide-y divide-white/10 md:grid-cols-4 md:divide-x md:divide-y-0">{features.map(({ title, copy, icon: Icon }) => <article key={title} className="px-5 py-5 md:px-6"><Icon className="h-6 w-6 text-[#75b9f5]" strokeWidth={1.5} /><h2 className="mt-2.5 text-[17px] font-semibold text-white">{title}</h2><p className="mt-1.5 max-w-[13rem] text-[13px] leading-5 text-fog">{copy}</p></article>)}</div></Container></section>

    <section id="timeline" className="relative scroll-mt-20 py-12 md:py-14"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(40,91,140,0.18),transparent_24%)]" /><Container><div className="relative text-center"><p className="font-meta text-[10px] uppercase tracking-[0.28em] text-[#91b6d8]">One track · many versions · one creative history</p><h2 className="mt-2 text-4xl font-semibold text-white md:text-5xl">From idea to release.</h2><p className="mt-1.5 text-[16px] text-fog">A visual timeline of your track&apos;s evolution.</p></div>
      <div className="relative mt-8 hidden lg:block"><div className="grid grid-cols-5 gap-3">{stages.map((stage) => <div key={stage.title} className="h-[87px] text-center"><p className="whitespace-pre-line font-display text-[13px] leading-[1.12] tracking-[0.03em] text-white/80">{stage.annotation}</p><ArrowDown className="mx-auto mt-1 h-3.5 w-3.5 text-white/65" /></div>)}</div><div className="absolute left-[8%] right-[3%] top-[94px] h-px bg-white/80"><ArrowRight className="absolute -right-4 -top-2 h-4 w-4 text-white/80" /></div><div className="relative grid grid-cols-5 gap-3">{stages.map((stage, index) => <article key={stage.title} className="relative pt-7"><span className="absolute left-1/2 top-[-8px] h-4 w-4 -translate-x-1/2 rounded-full border-2 border-white bg-[#3d8cda] shadow-[0_0_0_4px_rgba(61,140,218,0.2)]" /><StageDetail stage={stage} index={index} /></article>)}</div></div>
      <div className="relative mt-9 space-y-8 lg:hidden"><div className="absolute bottom-4 left-[7px] top-3 w-px bg-[linear-gradient(#7dbfff,rgba(100,161,215,0.25))]" />{stages.map((stage, index) => <article key={stage.title} className="relative grid grid-cols-[28px_minmax(0,1fr)] gap-3"><span className="relative z-10 mt-1 h-4 w-4 rounded-full border-2 border-white bg-[#3d8cda] shadow-[0_0_0_4px_rgba(61,140,218,0.2)]" /><div><p className="mb-2 whitespace-pre-line font-display text-xs leading-4 text-white/70">{stage.annotation}</p><StageDetail stage={stage} index={index} /></div></article>)}</div>
    </Container></section>

    <section className="pb-6"><Container><div className="grid gap-6 rounded-2xl border border-[#5a7999]/35 bg-[linear-gradient(100deg,rgba(6,18,33,0.95),rgba(4,10,20,0.96))] p-6 shadow-[0_18px_45px_rgba(0,0,0,0.28)] md:grid-cols-[84px_minmax(0,1fr)_190px] md:items-center md:p-7"><Disc3 className="h-16 w-16 text-white md:h-20 md:w-20" strokeWidth={1.05} /><div><p className="font-meta text-[10px] uppercase tracking-[0.28em] text-[#91b6d8]">More than a release</p><h2 className="mt-2 text-3xl font-semibold uppercase text-white md:text-[34px]">A record of your creativity</h2><p className="mt-3 max-w-3xl text-[13px] leading-5 text-fog">Most platforms only care about the finished track. Fully Open Records preserves everything that came before it. Track Version Control gives every recording, experiment, setup and decision a place in the history of the song.</p></div><div className="flex flex-col gap-3"><Link href="/signup"><Button className="w-full">Start Your Journey</Button></Link><Link href="/about" className="inline-flex items-center justify-center gap-2 text-[13px] text-[#91b6d8] hover:text-white">Explore Fully Open Records <ArrowRight className="h-3.5 w-3.5" /></Link></div></div></Container></section>
  </main>;
}
