CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  account_type TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE artists ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE artists ADD COLUMN profile_image TEXT;
ALTER TABLE artists ADD COLUMN banner_image TEXT;
ALTER TABLE artists ADD COLUMN location TEXT;
ALTER TABLE artists ADD COLUMN plan TEXT NOT NULL DEFAULT 'free';
ALTER TABLE artists ADD COLUMN admin_override INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX artists_user_id_idx ON artists(user_id);

CREATE TABLE songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  artist_id INTEGER,
  artist_name TEXT NOT NULL,
  title TEXT NOT NULL,
  slug TEXT,
  audio_url TEXT,
  duration INTEGER,
  cover_image TEXT,
  is_radio_eligible INTEGER NOT NULL DEFAULT 0,
  radio_selected INTEGER NOT NULL DEFAULT 0,
  approved_for_radio INTEGER NOT NULL DEFAULT 0,
  play_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  artist_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  video_url TEXT NOT NULL,
  thumbnail_url TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

CREATE TABLE photos (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  artist_id INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  alt TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

CREATE TABLE favourite_songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  song_id INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX favourite_songs_user_song_idx ON favourite_songs(user_id, song_id);
