CREATE TABLE IF NOT EXISTS albums (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  artist_id INTEGER NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  release_date TEXT,
  description TEXT,
  cover_art TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS press_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  artist_id INTEGER NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  publication TEXT NOT NULL,
  press_date TEXT,
  article_link TEXT,
  excerpt TEXT,
  feature_image TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE songs ADD COLUMN album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL;
ALTER TABLE songs ADD COLUMN description TEXT;
